Fix SimplifyFormRenderingRector replacing calls other than createView()
rectorphp/rector-symfony pull request #489
Opened 2023-07-04 11:50 UTC by adlpz

The SimplifyFormRenderingRector was replacing calls to methods other than ->createView(), which is no longer required in Symfony 6.2, e.g. calls to ->getData().

These are not deprecated and there's no reason to remove them, and in fact the blanket rule of removing any method calls of FormInterface parameters of the container $this->render() function is too wide and could lead to breakage.

2023-07-04 11:53 UTC, samsonasik requested changes
please add test case at https://github.com/rectorphp/rector-symfony/tree/main/rules-tests/Symfony62/Rector/MethodCall/SimplifyFormRenderingRector/Fixture

2023-07-06 15:12 UTC, adlpz commented
Wooops, I uploaded the base test case I wrote first. Fixed.

2023-07-06 15:13 UTC, samsonasik approved these changes

2023-07-06 15:14 UTC, adlpz commented
Wooops, I uploaded the base test case I wrote first. Fixed.

2023-07-06 15:15 UTC, merged